### ISSUE TITLE
Resume training报错

### ISSUE THREAD

**Issue by dongfengxijian** [SCZwangxiao/RTQ-MM2023#5] opened 2024-01-27 03:39 UTC
您好，我在根据code examples命令'bash run_scripts/dist_train.sh <path_to_your_config> $numGPU --options run.resume_ckpt_path=<path_to_latest_checkpoint>'进行resume training时候遇到了错误。
![image](https://github.com/SCZwangxiao/RTQ-MM2023/assets/24863806/ccbec964-fb3f-46ec-bb5e-80de5ed4951d)
我想请教一下，该怎么解决？

**Comment by SCZwangxiao** [comment] 2024-01-31 03:17
原因已找到。直接原因是checkpoint里缺少momentum模型的参数。根因是LAVIS框架不保存不带梯度的参数。相关issue在LAVIS repo居然挂了1年：https://github.com/salesforce/LAVIS/issues/153

已在新的[commit](https://github.com/SCZwangxiao/RTQ-MM2023/commit/ab5aaeb75e1aadd73e4f29ab57dfac23846260b4)修复。

----

Reason found. The direct cause is: parameters of momentum model are missing. Root cause is: LAVIS framework does not save parameters without gradient. There is also an issue in LAVIS repo https://github.com/salesforce/LAVIS/issues/153.

Fixed in the latest [commit](https://github.com/SCZwangxiao/RTQ-MM2023/commit/ab5aaeb75e1aadd73e4f29ab57dfac23846260b4)

**Closed as completed by SCZwangxiao** 2024-01-31 03:17 UTC
Labels: bug
